/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "LCD.h"
#include "Motor_Stop.h"
#include "UART.h"
#include "Clock_1.h"
#include "Clock_5.h"
#include "PWM_Motor.h"
#include "Motor_aliases.h"
#include "Motor.h"
#include "Timer_Motor.h"
#include "Video_Out_aliases.h"
#include "Video_Out.h"
#include "Vert_Sync_aliases.h"
#include "Vert_Sync.h"
#include "Timer_Edge.h"
#include "Comp_Black.h"
#include "Ref.h"
#include "Video_in_aliases.h"
#include "Video_in.h"
#include "turn.h"
#include "PWM_Servo.h"
#include "Servo_aliases.h"
#include "Servo.h"
#include "Clock_2.h"
#include "Clock_3.h"
#include "Horiz_Sync_aliases.h"
#include "Horiz_Sync.h"
#include "Pin_1_aliases.h"
#include "Pin_1.h"
#include "IRServo_aliases.h"
#include "IRServo.h"
#include "PWM_IRServo.h"
#include "Clock_4.h"
#include "Fan_1_aliases.h"
#include "Fan_1.h"
#include "PWM_Fan.h"
#include "Fan_2_aliases.h"
#include "Fan_2.h"
#include "Servo_1_aliases.h"
#include "Servo_1.h"
#include "Servo_2_aliases.h"
#include "Servo_2.h"
#include "PWM_FanServos.h"
#include "Temp_received.h"
#include "UART_Mega.h"
#include "LCD_LCDPort_aliases.h"
#include "LCD_LCDPort.h"
#include "UART_IntClock.h"
#include "UART_Mega_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

